import {
  FiGrid,
  FiUsers,
  FiUpload,
  FiAward,
  FiCheckSquare,
  FiBarChart2,
  FiCalendar,
  FiBell,
  FiFolder,
  FiSettings,
  FiFileText,
  FiPieChart,
  FiClipboard,
  FiHelpCircle,
} from "react-icons/fi";

export const NAV_ITEMS = [
  { label: "Dashboard", to: "/dashboard", icon: FiGrid, available: true },
  { label: "Registrations", to: "/registrations", icon: FiUsers, available: true },
  { label: "Submissions", to: "/submissions", icon: FiUpload, available: true },
  { label: "Problem Statements", to: "/problem-statements", icon: FiHelpCircle, available: true },
  { label: "Judges", to: "/judges", icon: FiAward, available: true },
  { label: "Evaluation", to: "/evaluation", icon: FiCheckSquare, available: true },
  { label: "Ranking", to: "/ranking", icon: FiBarChart2, available: true },
  { label: "Presentation Schedule", to: "/schedule", icon: FiCalendar, available: true },
  { label: "Announcements", to: "/announcements", icon: FiBell, available: true },
  { label: "Resources", to: "/resources", icon: FiFolder, available: true },
  { label: "Reports", to: "/reports", icon: FiFileText, available: true },
  { label: "Analytics", to: "/analytics", icon: FiPieChart, available: true },
  { label: "Audit Logs", to: "/audit-logs", icon: FiClipboard, available: true },
  { label: "Settings", to: "/settings", icon: FiSettings, available: true },
];
